AWSTemplateFormatVersion: "2010-09-09"
Transform:
    - AWS::LanguageExtensions

Parameters:
  ProductName:
    Type: String
    Description: The name of the product
  EnvironmentCode:
    Type: String
    Default: 'test'
    AllowedValues:
      - test
      - stg
      - prod
      - sandbox
    Description: The environment code used in the naming of all AWS services.
  WebAppImage:
    Type: String
    Description: The image of the web app
  DiscordPublicKey:
    Type: String
    Description: The public key of the discord bot
  DiscordBotToken:
    Type: String
    Description: The token of the discord bot
  GeocodingApiKey:
    Type: String
    Description: The API key for the geocoding service


Description: 'This template deploys the cloud infrastructure for the BOM usage reporter web app.'

Conditions:
  IsProduction: !Equals
    - !Ref EnvironmentCode
    - prod

Resources:
  # # # # # # # # # # # # # # #
  # # # # Lambda web app  # # #
  # # # # # # # # # # # # # # #

  ScraperLambda:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      Code:
        ImageUri: !Ref WebAppImage
      Description: "Woningbot Scraper"
      FunctionName:
        Fn::Sub: "lambda-${EnvironmentCode}-${ProductName}-scraper"
      MemorySize: 1024
      Timeout: 600
      PackageType: Image
      Role: !GetAtt LambdaIAMRole.Arn
      Environment:
        Variables:
          DISCORD_PUBLIC_KEY: !Ref DiscordPublicKey
          DISCORD_BOT_TOKEN: !Ref DiscordBotToken #TODO: secure this token
          GEOCODING_API_KEY: !Ref GeocodingApiKey #TODO: secure this token
          SUBSCRIBERS_TABLE: !Ref SubscribersTable
          HOUSES_TABLE: !Ref HousesTable


  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ScraperLambda.Arn
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt InvokeRule.Arn

  InvokeRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Scrape every 4 minutes."
      Name: "scrape-rule"
      #RoleArn: String
      ScheduleExpression: "rate(10 minutes)"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt ScraperLambda.Arn
          Id:
            Fn::Sub: "${ProductName}-scraper-lambda"
#          RoleArn: String

  LambdaUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      Cors:
        AllowCredentials: true
        #        AllowHeaders:
        #          - String
        AllowMethods:
          - POST
        AllowOrigins:
          - "*"
        MaxAge: 0
      InvokeMode: BUFFERED
      TargetFunctionArn: !GetAtt ScraperLambda.Arn

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunctionUrl
      FunctionName: !GetAtt ScraperLambda.Arn
      FunctionUrlAuthType: NONE
      Principal: "*"

  SubscribersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: channel_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: channel_id
          KeyType: HASH
      TableClass: STANDARD
      TableName:
        Fn::Sub: "dynamodb-${EnvironmentCode}-${ProductName}-subscribers"

  HousesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: address
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: address
          KeyType: HASH
      TableClass: STANDARD
      TableName:
        Fn::Sub: "dynamodb-${EnvironmentCode}-${ProductName}-houses"

  LambdaIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName:
        Fn::Sub: "iam-${AWS::Region}-${EnvironmentCode}-${ProductName}-lambda-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'root'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: arn:aws:logs:*:*:*
        - PolicyName: 'DynamoDB'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:BatchGetItem"
                  - "dynamodb:BatchWriteItem"
                  - "dynamodb:UpdateTimeToLive"
                  - "dynamodb:PutItem"
                  - "dynamodb:PartiQLSelect"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:GetItem"
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:UpdateTable"
                  - "dynamodb:GetRecords"
                Resource:
                  - !GetAtt SubscribersTable.Arn
                  - !GetAtt HousesTable.Arn
